name: agileBase
favicon: null
layout_spectrum: 0.4682
typography_spectrum: 0.1492
title: 'agile:food - A game-changer in food'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96c45b'
    - '#3c96ac'
    - '#a93456'
    - '#fffffe'
    - '#0a0c0a'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
