name: agileBase
favicon: null
layout_spectrum: 0.49453
typography_spectrum: 0.66566
title: agileBase - business agility through technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#96c45b'
    - '#aa3555'
    - '#3e97ac'
    - '#040604'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.027850974816828966
purpose: []
