name: agileBase
favicon: null
layout_spectrum: 0.46628
typography_spectrum: 0.34573
title: 'agile:food - A game-changer in food'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1eb79c'
    - '#5a3664'
    - '#f7ac42'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
