name: agileBase
favicon: null
layout_spectrum: 0.3001
typography_spectrum: 0.2282
title: A game-changer in food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101112'
    - '#f2f4f1'
    - '#b3cce6'
    - '#969798'
    - '#424344'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
