name: agileBase
favicon: null
layout_spectrum: 0.78461
typography_spectrum: 0.2282
title: Go faster in food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f7373'
    - '#1eb79c'
    - '#5a3664'
    - '#f7ac42'
    - '#9dcc52'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
