name: agileBase
favicon: null
layout_spectrum: 0.4682
typography_spectrum: 0.1492
title: 'agile:npdTech - A game-changer in food'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7ac42'
    - '#9dcc52'
    - '#5a3664'
    - '#6f7373'
    - '#1eb79c'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
